### PR TITLE
Use AWS SDK v3

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ruanltbg** [comment]
@tob1k the `aws-sdk` is already on  `3.53`

**Comment by ghost** [comment]
@ruanltbg Yeah you're right.

Seems like the issue is because the refile-s3 version hasn't been bumped in the gempsec, the 0.2.0 version of the gem is what gets served up, and it's still locked in the gemspec to use the aws-sdk v2

**Comment by ruanltbg** [comment]
@jnicklas can you take a look at this PR?

**Comment by sobrinho** [comment]
Thanks!

**Pull request merged**
