### PR TITLE
Raise exception for invalid s3 credentials

### PR DESCRIPTION
**Pull request by sobrinho**
See refile/refile#454

### CODE REVIEW

**Comment by sobrinho** [comment]
@jnicklas see if that's the way to go.

Basically we need better error messages due to typos instead of strange exceptions.

Does makes sense?

**Comment by klausbadelt** [comment]
AWS credentials as options should be actually considered optional (see other pull requests like #29 #18. Recommended on EC2 is actually instance profiles. See also [AWS SDK configuration](http://docs.aws.amazon.com/sdkforruby/api/#Configuration).

**Comment by sobrinho** [comment]
So, maybe in that case we could create a special value like `Refile::S3::NO_VALUE`, I don't know.

What you suggest?

We must have better exception messages.

**Comment by filmhubhq** [comment]
Doesn't AWS SDK already raise exceptions for missing configuration?

**Comment by sobrinho** [comment]
Not sure but on refile/refile#454 you will see that the error appears on refile itself, not on SDK.

**Comment by sobrinho** [comment]
Closing, if we found a better way to do that, a new pull request will be done.

**Pull request closed without merging**
